config-version: 2

name: 'sage_intacct'
version: '0.1.0'

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  sage_intacct:
    +materialized: table
    +schema: sage_intacct
    intermediate:
      +materialized: table 

vars:
  # account_pass_through_columns: []
  # profit_and_loss_pass_through_columns: []
  # gl_pass_through_columns: []
  
  sage_intacct:
    gl_detail: "{{ ref('stg_sage_intacct__gl_detail') }}"
    gl_account: "{{ ref('stg_sage_intacct__gl_account') }}"
    ap_bill_item: "{{ ref('stg_sage_intacct__ap_bill_item') }}"
    ap_bill: "{{ ref('stg_sage_intacct__ap_bill') }}"
    ar_invoice_item: "{{ ref('stg_sage_intacct__ar_invoice_item') }}"
    ar_invoice: "{{ ref('stg_sage_intacct__ar_invoice') }}"


analysis-paths: ["analysis"]

clean-targets:
- target
- dbt_modules
- dbt_packages