config-version: 2

name: 'sage_intacct'
version: '0.1.0'

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  sage_intacct:
    +materialized: table
    +schema: sage_intacct
    intermediate:
      +materialized: table #do these need to be tables? Can they be ephemeral or views? Or would that impact performance?

vars:
  sage_intacct:
    gl_detail: "{{ ref('stg_sage_intacct__gl_detail') }}"
    gl_account: "{{ ref('stg_sage_intacct__gl_account') }}"
    ap_bill_item: "{{ ref('stg_sage_intacct__ap_bill_item') }}"
    ap_bill: "{{ ref('stg_sage_intacct__ap_bill') }}"
    ar_invoice_item: "{{ ref('stg_sage_intacct__ar_invoice_item') }}"
    ar_invoice: "{{ ref('stg_sage_intacct__ar_invoice') }}"


analysis-paths: ["analysis"]

## The clean-targets is not needed
clean-targets:
- target
- dbt_modules
- dbt_packages