name: 'sage_intacct_integration_tests'
version: '0.1.0'
config-version: 2

profile: 'integration_tests'

models: 
  sage_intacct:
    +materialized: table
    intermediate:
      +materialized: table

  sage_intacct_source:
    +materialized: table
    tmp:
      +materialized: view

vars:
  sage_intacct:
    gl_detail:                    "{{ ref('stg_sage_intacct__gl_detail') }}"
    gl_account:                   "{{ ref('stg_sage_intacct__gl_account') }}"
    ap_bill_item:                 "{{ ref('stg_sage_intacct__ap_bill_item') }}"
    ap_bill:                      "{{ ref('stg_sage_intacct__ap_bill') }}"
    ar_invoice_item:              "{{ ref('stg_sage_intacct__ar_invoice_item') }}"
    ar_invoice:                   "{{ ref('stg_sage_intacct__ar_invoice') }}"

  sage_intacct_source:
    gl_detail:                    "{{ ref('sage_intacct__gl_detail') }}"
    gl_account:                   "{{ ref('sage_intacct__gl_account') }}"
    ap_bill_item:                 "{{ ref('sage_intacct__ap_bill_item') }}"
    ap_bill:                      "{{ ref('sage_intacct__ap_bill') }}"
    ar_invoice_item:              "{{ ref('sage_intacct__ar_invoice_item') }}"
    ar_invoice:                   "{{ ref('sage_intacct__ar_invoice') }}"
    
seeds:
    +quote_columns: "{{ true if target.type == 'redshift' else false }}"

clean-targets:
    - target
    - dbt_modules